### ISSUE TITLE
Text editor not rendering tab character

### ISSUE THREAD

**Issue by lhiginbotham** [gitextensions/ICSharpCode.TextEditor#22]
## Current behaviour

When rewording a commit using Git Extensions, I've found that tab characters are not rendering in the default text editor (though the characters do exist within the commit message and can be seen when doing `git log`).

## Expected behaviour

The text editor should render whitespace whenever there are tab characters in the loaded document.

## Steps to reproduce

1. Go to a commit entry in the commit log in Git Extensions
2. Right-click the commit entry > Advanced > Reword commit
3. Edit the text of the commit and notice that adding tabs has no effect on the rendered text.  For example, if you have a line with the text "abc" with your cursor between 'a' and 'b', pressing tab 3 times will do nothing, but you will need to press the Delete key 4 times in order to delete the 'a' character.  This shows that the tab characters are being processed but just not rendered.

## Screenshots

In the text editor, I put a tab between 'w' and 'o' of "Reworded" and a tab between 'm' and 'i' of "commit".
![image](https://user-images.githubusercontent.com/14078392/83366185-7ce66400-a37b-11ea-9fd0-895b9aeb1424.png)

How it appears in the Git log:
![image](https://user-images.githubusercontent.com/14078392/83366249-cb93fe00-a37b-11ea-8136-cd8b35ad1b97.png)

## Did this work in previous version

Not sure

## Environment

- GitExtensions version: 3.4.0.9381
- GIT version: 2.26.0.windows.1
- OS version: Windows 10 / Microsoft Windows NT 6.2.9200.0
- .NET version: 4.8.4180.0

**Comment by lhiginbotham** [comment]
@RussKie 
FYI, the commit entries in Git Extensions does not render tabs either; is this an issue or is it the desired behavior?

**Comment by RussKie** [comment]
I agree with you. I think it's a bug, I personally can't see this being a
desired behaviour in the context of the app.
